### ISSUE TITLE
not enough master nodes discovered during pinging, elastic search

### ISSUE THREAD

**Issue by ximbal** [temporalio/helm-charts#131]
I just did a fresh install using your helm chart
```

org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onTimeout(ClusterStateObserver.java:322) [elasticsearch-6.8.8.jar:6.8.8] 
	at org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.onTimeout(ClusterStateObserver.java:249) [elasticsearch-6.8.8.jar:6.8.8] 
	at org.elasticsearch.cluster.service.ClusterApplierService$NotifyTimeout.run(ClusterApplierService.java:564) [elasticsearch-6.8.8.jar:6.8.8] 
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:681) [elasticsearch-6.8.8.jar:6.8.8] 
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?] 
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?] 
	at java.lang.Thread.run(Thread.java:832) [?:?] 
[2021-01-18T22:44:42,691][WARN ][o.e.d.z.ZenDiscovery     ] [elasticsearch-master-0] not enough master nodes discovered during pinging (found [[Candidate{node={elasticsearch-master-0}{fT0h0QSLRviF288vMzreMQ}{JIIqoPB_SD2J6Ugj3Cqu6w}{10.10.2.16}{10.10.2.16:9300}{ml.machine_memory=2147483648, xpack.installed=true, ml.max_open_jobs=20, ml.enabled=true}, clusterStateVersion=-1}]], but needed [2]), pinging again 

```

Any Suggestions? Thank you

**Comment by sramshaw-yolabs** [comment]
The default settings for the helm chart tries to run 3 ES nodes.  If you don't have 3 nodes in your k8s cluster/node pool, such as if you are running k8s locally, you can update the settings to only require 1 node.

In your values set:
```
elasticsearch:
  enabled: true
  replicas: 1
  minimumMasterNodes: 1
```
